#!/bin/sh

cat <<EOF
Test-Command: /usr/share/pkg-js-autopkgtest/runner require
Depends: @, nodejs, pkg-js-autopkgtest, ${pkg_nodejs_extra_depends:-}
Restrictions: superficial, skippable, ${pkg_nodejs_extra_restrictions:-}
Features: test-name=pkg-js-autopkgtest-require

Test-Command: /usr/share/pkg-js-autopkgtest/runner
Depends: @, @builddeps@, pkg-js-autopkgtest, ${pkg_nodejs_extra_depends:-}
Restrictions: allow-stderr, skippable, ${pkg_nodejs_extra_restrictions:-}
Features: test-name=pkg-js-autopkgtest
EOF
