#!/bin/sh

set -eu

if [ $# -gt 1 ]; then
  echo "usage: $(basename $0) [SOURCEDIR]"
  exit 128
fi

if [ -n "${1:-}" ]; then
  cd "${1}"
fi

for support_dir in \
  $(dirname $0)/support \
  /usr/local/share/autodep8/support \
  /usr/share/autodep8/support;
do
  if [ -d "$support_dir" ]; then
    for packagetype in $(find $support_dir -mindepth 1 -type d | xargs -n 1 basename); do
      if grep-dctrl --quiet -F XS-Testsuite,Testsuite autopkgtest-pkg-$packagetype debian/control || $support_dir/$packagetype/detect; then
        $support_dir/$packagetype/generate
        exit 0
      fi
    done
  fi
done

exit 1
