#!/bin/sh

# Stderr is required because many go tools output status info to stderr.
cat <<EOF
Test-Command: /usr/bin/dh_golang_autopkgtest
Depends: @, @builddeps@, dh-golang, ${pkg_go_extra_depends:-}
Restrictions: allow-stderr, ${pkg_go_extra_restrictions:-}
Features: test-name=dh-golang-autopkgtest
EOF
