#!/bin/sh

extra_arch=""
if [ x"${pkg_perl_architecture:-}" != x ]; then
    extra_arch="Architecture: ${pkg_perl_architecture}"
fi


cat <<EOF
Test-Command: /usr/share/pkg-perl-autopkgtest/runner build-deps
Depends: @, @builddeps@, pkg-perl-autopkgtest, ${pkg_perl_extra_depends:-}
Restrictions: skippable, ${pkg_perl_extra_restrictions:-}
Features: test-name=autodep8-perl-build-deps
${extra_arch}

Test-Command: /usr/share/pkg-perl-autopkgtest/runner runtime-deps
Depends: @, pkg-perl-autopkgtest, ${pkg_perl_extra_depends:-}
Restrictions: skippable, superficial, ${pkg_perl_extra_restrictions:-}
Features: test-name=autodep8-perl
${extra_arch}

Test-Command: /usr/share/pkg-perl-autopkgtest/runner runtime-deps-and-recommends
Depends: @, pkg-perl-autopkgtest, ${pkg_perl_extra_depends:-}
Restrictions: needs-recommends, skippable, superficial, ${pkg_perl_extra_restrictions:-}
Features: test-name=autodep8-perl-recommends
${extra_arch}
EOF

