#!/bin/sh

. $(dirname $0)/../common

recommends=$(parse_control 'Recommends')

cat <<EOF
Test-Command: /usr/share/pkg-perl-autopkgtest/runner build-deps
Depends: @, @builddeps@, pkg-perl-autopkgtest
Features: test-name=autodep8-perl-build-deps

Test-Command: /usr/share/pkg-perl-autopkgtest/runner runtime-deps
Depends: @, pkg-perl-autopkgtest
Features: test-name=autodep8-perl

Test-Command: /usr/share/pkg-perl-autopkgtest/runner runtime-deps-and-recommends
Depends: @, $recommends pkg-perl-autopkgtest
Features: test-name=autodep8-perl-recommends
EOF
