#!/bin/sh

set -eu

test_package_type=$(dirname $0)/test-package-type

failed=""
rc=0
while read pkgtype pkg; do
  case "${pkgtype}" in
    "#"*)
      :
      ;;
    *)
      if ! $test_package_type "${pkgtype}" "${pkg}"; then
        failed="${failed} ${pkgtype}"
        rc=1
      fi
      ;;
  esac
done < examples.in

if [ -n "${failed}" ]; then
  echo
  echo "FAILED:${failed}"
fi
exit "$rc"
