#!/bin/sh

. $(dirname $0)/../common

recommends=$(parse_control 'Recommends')

cat <<EOF
Test-Command: /usr/share/dh-r/pkg-r-autopkgtest
Depends: @, $recommends pkg-r-autopkgtest
Restrictions: allow-stderr
EOF
