#!/bin/sh

. $(dirname $0)/../common

rtestdeps=$(parse_descr_r)

cat <<EOF
Test-Command: /usr/share/dh-r/pkg-r-autopkgtest
Depends: @, $rtestdeps pkg-r-autopkgtest, ${pkg_r_extra_depends:-}
Restrictions: allow-stderr, ${pkg_r_extra_restrictions:-}
Features: test-name=pkg-r-autopkgtest
EOF

if [ x"${pkg_r_architecture:-}" != x ]; then
    echo Architecture: "${pkg_r_architecture}"
fi
