#!/bin/sh

### Select only the packages from Octave-Forge.  The detection is based on
### the existence of an inst/ directory (which contains the *.m to be
### tested) and a DESCRIPTION file, besides the name of the source package,
### which must start with ""octave-"".

test -d inst								\
    && test -f DESCRIPTION						\
    && grep-dctrl --quiet -F Source -r '^octave-.*$' debian/control
