#!/bin/sh

# Maintainer: Sean Whitton <spwhitton@spwhitton.name>

# We check that: this package uses dh_elpa, debhelper compat level is
# at least 10 (see dh_elpa_test(1)), and the user hasn't disabled
# dh_elpa_test, and that there is actually a testsuite to run

set -e

if test -e debian/compat; then
    # ^ check that the file exists first, so that if it doesn't the
    # following cat doesn't produce stderr which disrupts other
    # test/*_test.sh
    test "$(cat debian/compat)" -ge 10
elif (! grep-dctrl -q -F Build-Depends debhelper-compat debian/control) 2>/dev/null; then
    # ^ mere presence of debhelper-compat build-dep implies compat >10
    exit 1
fi
(! grep -q ".*DH_ELPA_TEST_DISABLE.*" debian/rules) 2>/dev/null
(! grep -q "^disabled[ ]*=" debian/elpa-test) 2>/dev/null
grep-dctrl -q -F Build-Depends dh-elpa debian/control
( grep -q -r ".*(ert-deftest.*" . || \
        grep-dctrl -q -F Build-Depends elpa-buttercup debian/control )
