#!/bin/sh

# Maintainer: Sean Whitton <spwhitton@spwhitton.name>

# We need rw-build-tree because dh_elpa_test will rename non-test .el
# files so that Emacs won't load them.  This ensures we're testing the
# installed binary package rather than the source package.

cat <<EOF
Test-Command: dh_elpa_test --autopkgtest
Depends: @, @builddeps@
Restrictions: rw-build-tree
EOF
