#!/bin/sh

# Maintainer: Sean Whitton <spwhitton@spwhitton.name>

# We need rw-build-tree because dh_elpa_test will rename non-test .el
# files so that Emacs won't load them.  This ensures we're testing the
# installed binary package rather than the source package.

cat <<EOF
Test-Command: dh_elpa_test --autopkgtest
Depends: @, @builddeps@, ${pkg_elpa_extra_depends:-}
Restrictions: rw-build-tree, ${pkg_elpa_extra_restrictions:-}
Features: test-name=dh-elpa-test-autopkgtest
EOF

if [ x"${pkg_elpa_architecture:-}" != x ]; then
    echo Architecture: "${pkg_elpa_architecture}"
fi
