#!/bin/sh

set -e

# remove debhelper and gem2deb
if [ -f debian/control ]; then
  builddeps=$(
    grep-dctrl -n -s Build-Depends -F Build-Depends -r . debian/control \
    | grep -v '^\s*#' \
    | sed -e 's/,\s*/\n/g; s/^\s*//' \
    | sed -e 's/\s*<[^)]*>\s*$//' \
    | sed '/^\s*$/ d; /debhelper/ d; /gem2deb/ d; s/\n/, /' \
    | tr '\n' ', ')
else
  builddeps=''
fi

cat <<EOF
Test-Command: gem2deb-test-runner --autopkgtest --check-dependencies 2>&1
Depends: @, $builddeps gem2deb-test-runner
Features: test-name=gem2deb-test-runner
EOF
